using UnityEngine;
using UnityEngine.Events;

namespace Events
{
    [System.Serializable]
    public class UnityEventWithParameters : UnityEvent<Component, object> {}
    public class CrossObjectEventWithDataListener : MonoBehaviour
    {
        public CrossObjectEventWithDataSO gameEvent;
        public UnityEventWithParameters responseOnTrigger; 

        private void OnEnable() {
            gameEvent.AddListener(this);
        }

        private void OnDisable() {
            gameEvent.RemoveListener(this);
        }

        public virtual void TriggerEvent(Component sender, params object[] data) {

            responseOnTrigger?.Invoke(sender, data);
        }
    }   
}